name: exulansis theory
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59319
title: exulansis theory
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#cae4fd'
    - '#9ab5e0'
    - '#7b89a4'
    - '#4f565e'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
