name: exulansis theory
favicon: null
layout_spectrum: 0.6825168337672949
typography_spectrum: 0.7822300044354051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7326867852825671
  lightness: 0.45858553424477577
  saturation: 0.261728955199942
  rhythmicContrast: 0.9152320609427989
purpose: []
