title: exulansis theory
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0.6875
  rhythmicContrast: 0
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#947a7d'
    - '#e5d0cb'
    - '#272530'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: exulansis theory
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.59319
layout_spectrum: 1
