name: exulansis theory
favicon: null
layout_spectrum: 0.00992
typography_spectrum: 0.45463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#947a7d'
    - '#e5d0cb'
    - '#272530'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
